on:
  reddit:
    url: https://reddit.com/r/news/
    config:
      active: true
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: '${{ secrets.DISCORD_WEBHOOK_NEWS }}'
          TEXT_MESSAGE: 'Reddit: ${{on.reddit.outputs.title }} ${{ on.reddit.outputs.link }}'
        uses: Ilshidur/action-discord@master
        with:
          args: '${{env.TEXT_MESSAGE}}'
